dataset: mot

train_split: mot17_train_coco
val_split: mot17_train_cross_val_frame_0_5_to_1_0_coco

# mot_path_train: data/MOT17
# mot_path_val: data/MOT17

mot_path_train: /home/ljq/UAV-Tracking/Dataset/MOT17
mot_path_val: /home/ljq/UAV-Tracking/Dataset/MOT17

# resume: models/r50_deformable_detr_plus_iterative_bbox_refinement-checkpoint_hidden_dim_288.pth
resume: models/trackformer_models_v1/mot17_deformable_multi_frame/checkpoint_epoch_50.pth

epochs: 1
lr_drop: 10