dataset: mot

train_split: mot_fly_train_coco
val_split: mot_fly_train_cross_val_frame_0_5_to_1_0_coco

# mot_path_train: data/MOT17
# mot_path_val: data/MOT17

mot_path_train: /home/ljq/UAV-Tracking/Dataset/MOT_FLY_V0.4/MOT_FLY_V0.3
mot_path_val: /home/ljq/UAV-Tracking/Dataset/MOT_FLY_V0.4/MOT_FLY_V0.3

# resume: models/r50_deformable_detr_plus_iterative_bbox_refinement-checkpoint_hidden_dim_288.pth
resume: 

epochs: 20
lr_drop: 10



